version: "3"

services:
  redis:
    image: redis
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - "6379:6379"

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: node-container
    command: npm start
    volumes:
      - ./server:/usr/app
    ports:
      - "3333:3333"
    environment:
      REDIS_HOST: redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/app
    stdin_open: true